export const JWT_SECRET = process.env.JWT_SECRET || 'store-poc-dev-secret-change-me';

export const ROLES = {
  ADMIN: 'ADMIN',
  STORE_MANAGER: 'STORE_MANAGER',
  STORE_EXECUTIVE: 'STORE_EXECUTIVE',
  PURCHASE: 'PURCHASE',
  QUALITY: 'QUALITY',
  PRODUCTION: 'PRODUCTION',
  SALES: 'SALES',
  ACCOUNTS: 'ACCOUNTS',
  DISPATCH: 'DISPATCH',
  MANAGEMENT: 'MANAGEMENT',
  FINANCE: 'FINANCE',
  DESIGN_ENGINEER: 'DESIGN_ENGINEER',
  CHECKER: 'CHECKER',
  DESIGN_HEAD: 'DESIGN_HEAD',
  PRODUCTION_HEAD: 'PRODUCTION_HEAD',
  SHOP_FLOOR_ENGINEER: 'SHOP_FLOOR_ENGINEER',
  PROJECT_MANAGER: 'PROJECT_MANAGER',
  SITE_ENGINEER: 'SITE_ENGINEER',
  TRANSPORT: 'TRANSPORT',
};
